version: '3.7'
services:
  locus-frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    networks:
      - locus-network
    ports:
      - '4200:80'

  locus-backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    networks:
      - locus-network
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:root@locus_postgresql:5432/locus

  locus-postgresql:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=locus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - locus-network
    container_name: locus_postgresql

networks:
  locus-network:
    driver: bridge
