FROM node:12

ARG DATABASE_URL

ENV DATABASE_URL $DATABASE_URL
ENV PORT 80

# Create app directory
WORKDIR /usr/src/app
COPY . /usr/src/app

RUN cd /usr/src/app/dist/apps/api && npm install

CMD [ "node", "dist/apps/api/main.js" ]
