FROM node:14.15 AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build:api

# Create app directory
FROM node:14.15
WORKDIR /usr/src/app

ARG DATABASE_URL

ENV DATABASE_URL $DATABASE_URL
COPY --from=build /usr/src/app/dist/apps/api .

RUN npm install

CMD [ "node", "main.js" ]
