version: '3.7'
services:
  locus-backend:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - locus-backend-network
    ports:
      - '8080:4000'

networks:
  locus-backend-network:
    driver: bridge
